// components/game/CharacterPanel.tsx
/**
 * CharacterPanel - Full-screen player stats, equipment, and faction reputation view.
 *
 * Ported from legacy/angular-ui/character-panel.component.ts
 */

import * as React from 'react';
import { Modal, Pressable, View } from 'react-native';
import Animated, { FadeIn, FadeOut } from 'react-native-reanimated';

import { cn } from '@/lib/utils';
import {
  Text,
  Button,
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  Progress,
  Badge,
  ScrollArea,
  Separator,
} from '@/components/ui';
import { gameStore } from '@/src/game/store/webGameStore';
import type { EquipmentSlot, InventoryItem } from '@/src/game/store/types';
import { getRarityColor } from '@/src/game/data/schemas/item';
import { getItem } from '@/src/game/data/items';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const EQUIPMENT_SLOTS: { slot: EquipmentSlot; label: string; icon: string }[] = [
  { slot: 'weapon', label: 'Main Weapon', icon: '\u{1F52B}' },
  { slot: 'offhand', label: 'Sidearm', icon: '\u{1F5E1}' },
  { slot: 'head', label: 'Hat', icon: '\u{1F3A9}' },
  { slot: 'body', label: 'Vest', icon: '\u{1F9E5}' },
  { slot: 'accessory', label: 'Accessory', icon: '\u{1F48D}' },
];

/** Simplified faction list for the character panel. */
const DISPLAY_FACTIONS = [
  { id: 'law_enforcement', label: 'Lawmen' },
  { id: 'desperados', label: 'Outlaws' },
  { id: 'mining_consortium', label: 'Miners' },
  { id: 'cattle_barons', label: 'Ranchers' },
  { id: 'railroad_company', label: 'Railroad' },
] as const;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function getReputationColor(rep: number): {
  label: string;
  textClass: string;
  barClass: string;
} {
  if (rep >= 60) return { label: 'Allied', textClass: 'text-yellow-400', barClass: 'bg-yellow-500' };
  if (rep >= 20) return { label: 'Friendly', textClass: 'text-green-400', barClass: 'bg-green-500' };
  if (rep >= -9) return { label: 'Neutral', textClass: 'text-gray-400', barClass: 'bg-gray-500' };
  if (rep >= -30) return { label: 'Unfriendly', textClass: 'text-orange-400', barClass: 'bg-orange-500' };
  return { label: 'Hostile', textClass: 'text-red-400', barClass: 'bg-red-500' };
}

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

function StatBar({
  label,
  current,
  max,
  variant,
}: {
  label: string;
  current: number;
  max: number;
  variant?: 'health' | 'xp' | 'default';
}) {
  const pct = max > 0 ? (current / max) * 100 : 0;
  return (
    <View className="gap-1">
      <View className="flex-row items-center justify-between">
        <Text variant="small" className="text-muted-foreground">
          {label}
        </Text>
        <Text variant="small" className="text-foreground">
          {Math.round(current)}/{max}
        </Text>
      </View>
      <Progress value={pct} variant={variant ?? 'default'} />
    </View>
  );
}

function EquipmentSlotRow({
  slot,
  label,
  icon,
  item,
  onUnequip,
}: {
  slot: EquipmentSlot;
  label: string;
  icon: string;
  item: InventoryItem | null;
  onUnequip: (slot: EquipmentSlot) => void;
}) {
  const itemDef = item ? getItem(item.itemId) : null;
  const rarityColor = itemDef ? getRarityColor(itemDef.rarity ?? 'common') : undefined;

  return (
    <Pressable
      className={cn(
        'flex-row items-center gap-3 rounded-md border border-border/50 bg-muted/30 px-3 py-2.5',
        item && 'active:bg-muted/60',
      )}
      onPress={() => item && onUnequip(slot)}
    >
      <Text className="text-lg">{icon}</Text>
      <View className="flex-1">
        <Text variant="caption" className="text-muted-foreground">
          {label}
        </Text>
        {item ? (
          <Text
            variant="small"
            style={rarityColor ? { color: rarityColor } : undefined}
          >
            {item.name}
          </Text>
        ) : (
          <Text variant="small" className="text-muted-foreground/50 italic">
            Empty
          </Text>
        )}
      </View>
    </Pressable>
  );
}

function FactionReputationRow({
  factionId,
  label,
  reputation,
}: {
  factionId: string;
  label: string;
  reputation: number;
}) {
  const { label: tierLabel, textClass, barClass } = getReputationColor(reputation);
  // Normalize reputation from -100..100 to 0..100 for the bar
  const barPercent = ((reputation + 100) / 200) * 100;

  return (
    <View className="gap-1">
      <View className="flex-row items-center justify-between">
        <Text variant="small" className="text-foreground">
          {label}
        </Text>
        <Text variant="caption" className={textClass}>
          {tierLabel}
        </Text>
      </View>
      <View className="h-2 w-full overflow-hidden rounded-full bg-muted">
        <View
          className={cn('h-full rounded-full', barClass)}
          style={{ width: `${Math.max(2, barPercent)}%` }}
        />
      </View>
    </View>
  );
}

// ---------------------------------------------------------------------------
// Main Component
// ---------------------------------------------------------------------------

export function CharacterPanel() {
  const isOpen = gameStore((s) => s.activePanel === 'character');
  const playerStats = gameStore((s) => s.playerStats);
  const playerName = gameStore((s) => s.playerName);
  const equipment = gameStore((s) => s.equipment);
  const togglePanel = gameStore((s) => s.togglePanel);
  const getEquippedItem = gameStore((s) => s.getEquippedItem);
  const unequipItem = gameStore((s) => s.unequipItem);
  const getEquipmentBonuses = gameStore((s) => s.getEquipmentBonuses);

  const bonuses = React.useMemo(() => getEquipmentBonuses(), [equipment, getEquipmentBonuses]);

  if (!isOpen) return null;

  return (
    <Modal transparent visible={isOpen} onRequestClose={() => togglePanel('character')}>
      <Animated.View
        entering={FadeIn.duration(200)}
        exiting={FadeOut.duration(150)}
        className="absolute inset-0 bg-black/70"
      >
        <View className="flex-1 px-4 py-12">
          <Card className="flex-1 border-frontier-leather/40">
            {/* Header */}
            <CardHeader className="flex-row items-center justify-between">
              <CardTitle>
                <Text variant="subheading">{playerName || 'Stranger'}</Text>
              </CardTitle>
              <Button
                variant="ghost"
                size="sm"
                onPress={() => togglePanel('character')}
              >
                <Text variant="small">Close</Text>
              </Button>
            </CardHeader>

            <ScrollArea className="flex-1" contentContainerClassName="pb-6">
              <CardContent className="gap-6">
                {/* ----- Player Stats ----- */}
                <View className="gap-3">
                  <Text variant="label" className="text-muted-foreground uppercase tracking-widest">
                    Vitals
                  </Text>

                  <View className="flex-row items-center gap-4">
                    <Badge variant="info">
                      <Text>Lv. {playerStats.level}</Text>
                    </Badge>
                    <Text variant="caption" className="text-foreground">
                      {playerStats.gold} Gold
                    </Text>
                  </View>

                  <StatBar
                    label="Health"
                    current={playerStats.health}
                    max={playerStats.maxHealth}
                    variant="health"
                  />
                  <StatBar
                    label="Stamina"
                    current={playerStats.stamina}
                    max={playerStats.maxStamina}
                  />
                  <StatBar
                    label="Experience"
                    current={playerStats.xp}
                    max={playerStats.xpToNext}
                    variant="xp"
                  />
                </View>

                <Separator />

                {/* ----- Equipment Bonuses ----- */}
                {(bonuses.damage > 0 || bonuses.defense > 0 || bonuses.accuracy > 0) && (
                  <>
                    <View className="flex-row gap-4">
                      {bonuses.damage > 0 && (
                        <Badge variant="danger">
                          <Text>+{bonuses.damage} DMG</Text>
                        </Badge>
                      )}
                      {bonuses.defense > 0 && (
                        <Badge variant="info">
                          <Text>+{bonuses.defense} DEF</Text>
                        </Badge>
                      )}
                      {bonuses.accuracy > 0 && (
                        <Badge variant="success">
                          <Text>+{bonuses.accuracy} ACC</Text>
                        </Badge>
                      )}
                    </View>
                    <Separator />
                  </>
                )}

                {/* ----- Equipment Slots ----- */}
                <View className="gap-3">
                  <Text variant="label" className="text-muted-foreground uppercase tracking-widest">
                    Equipment
                  </Text>
                  {EQUIPMENT_SLOTS.map(({ slot, label, icon }) => (
                    <EquipmentSlotRow
                      key={slot}
                      slot={slot}
                      label={label}
                      icon={icon}
                      item={getEquippedItem(slot)}
                      onUnequip={unequipItem}
                    />
                  ))}
                </View>

                <Separator />

                {/* ----- Faction Reputation ----- */}
                <View className="gap-3">
                  <Text variant="label" className="text-muted-foreground uppercase tracking-widest">
                    Reputation
                  </Text>
                  {DISPLAY_FACTIONS.map(({ id, label }) => (
                    <FactionReputationRow
                      key={id}
                      factionId={id}
                      label={label}
                      reputation={playerStats.reputation ?? 0}
                    />
                  ))}
                </View>
              </CardContent>
            </ScrollArea>
          </Card>
        </View>
      </Animated.View>
    </Modal>
  );
}

// src/app/game/ui/character-panel.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

import { getItem } from '@/data/items';
import { getRarityColor } from '@/data/schemas/item';
import type { EquipmentSlot } from '@/store';
import { GameStoreService } from '../services/game-store.service';

const EQUIPMENT_SLOTS: { slot: EquipmentSlot; label: string; icon: string }[] = [
  { slot: 'head', label: 'Hat', icon: 'M12 2l4 4h-8l4-4zm-6 6h12v2H6z' },
  { slot: 'body', label: 'Vest', icon: 'M6 2h12l-2 8v12H8V10L6 2z' },
  { slot: 'weapon', label: 'Weapon', icon: 'M14.5 17.5L3 6V3h3l11.5 11.5M13 19l6-6' },
  { slot: 'offhand', label: 'Offhand', icon: 'M12 1L3 5v6c0 5.55 3.84 10.74 9 12 5.16-1.26 9-6.45 9-12V5l-9-4z' },
  { slot: 'accessory', label: 'Trinket', icon: 'M12 8a6 6 0 100 12 6 6 0 000-12z' },
];

@Component({
  selector: 'app-character-panel',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './character-panel.component.html',
  styleUrls: ['./character-panel.component.scss'],
})
export class CharacterPanelComponent {
  readonly slots = EQUIPMENT_SLOTS;

  constructor(readonly gameStore: GameStoreService) {}

  get isOpen(): boolean {
    return this.gameStore.getState().activePanel === 'character';
  }

  close(): void {
    this.gameStore.actions().togglePanel('character');
  }

  get itemBonuses() {
    return this.gameStore.actions().getEquipmentBonuses();
  }

  getEquippedItem(slot: EquipmentSlot) {
    return this.gameStore.actions().getEquippedItem(slot);
  }

  unequip(slot: EquipmentSlot): void {
    this.gameStore.actions().unequipItem(slot);
  }

  getItemName(itemId?: string | null): string {
    if (!itemId) return 'Empty';
    return getItem(itemId)?.name ?? 'Unknown';
  }

  getRarityColor(rarity?: string): string {
    return getRarityColor(rarity ?? 'common');
  }
}

<div *ngIf="isOpen" class="fixed inset-0 z-50">
  <div class="absolute inset-0 bg-black/50" (click)="close()"></div>
  <div class="absolute inset-x-0 bottom-0 h-[85vh] sm:h-[75vh] bg-amber-950 border-t border-amber-800/60 rounded-t-2xl overflow-hidden" *ngIf="(gameStore.state$ | async) as state">
    <div class="p-3 border-b border-amber-800/50 flex items-center justify-between">
      <div class="flex items-center gap-2 text-amber-100">
        <svg class="w-5 h-5 text-amber-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
        </svg>
        <span class="text-sm sm:text-base">Outlaw</span>
      </div>
      <button class="text-amber-400 hover:text-amber-200" (click)="close()" aria-label="Close">
        ✕
      </button>
    </div>

    <div class="p-3 grid grid-cols-1 md:grid-cols-2 gap-4 h-[calc(85vh-56px)] overflow-y-auto">
      <div class="space-y-3">
        <div class="bg-amber-950/60 border border-amber-800/40 rounded-lg p-3">
          <div class="text-amber-100 font-semibold">{{ state.playerName }}</div>
          <div class="text-amber-400/80 text-xs">Level {{ state.playerStats.level }}</div>
        </div>

        <div class="bg-amber-950/60 border border-amber-800/40 rounded-lg p-3 space-y-3">
          <div>
            <div class="flex items-center justify-between text-xs text-amber-300">
              <span>Health</span>
              <span class="font-mono">{{ state.playerStats.health }} / {{ state.playerStats.maxHealth }}</span>
            </div>
            <div class="h-2 bg-amber-900/50 rounded overflow-hidden border border-amber-700/30">
              <div class="h-full bg-red-500" [style.width.%]="(state.playerStats.health / state.playerStats.maxHealth) * 100"></div>
            </div>
          </div>
          <div>
            <div class="flex items-center justify-between text-xs text-amber-300">
              <span>Stamina</span>
              <span class="font-mono">{{ state.playerStats.stamina }} / {{ state.playerStats.maxStamina }}</span>
            </div>
            <div class="h-2 bg-amber-900/50 rounded overflow-hidden border border-amber-700/30">
              <div class="h-full bg-amber-500" [style.width.%]="(state.playerStats.stamina / state.playerStats.maxStamina) * 100"></div>
            </div>
          </div>
          <div>
            <div class="flex items-center justify-between text-xs text-amber-300">
              <span>Experience</span>
              <span class="font-mono">{{ state.playerStats.xp }} / {{ state.playerStats.xpToNext }}</span>
            </div>
            <div class="h-2 bg-amber-900/50 rounded overflow-hidden border border-amber-700/30">
              <div class="h-full bg-amber-400" [style.width.%]="(state.playerStats.xp / state.playerStats.xpToNext) * 100"></div>
            </div>
          </div>
        </div>

        <div class="bg-amber-950/60 border border-amber-800/40 rounded-lg p-3 text-xs text-amber-300 space-y-1">
          <div>Attack: {{ state.playerStats.attack + itemBonuses.attack }}</div>
          <div>Defense: {{ state.playerStats.defense + itemBonuses.defense }}</div>
          <div>Accuracy: {{ state.playerStats.accuracy + itemBonuses.accuracy }}</div>
          <div>Crit: {{ state.playerStats.critChance + itemBonuses.critChance }}%</div>
        </div>
      </div>

      <div class="space-y-3">
        <div class="bg-amber-950/60 border border-amber-800/40 rounded-lg p-3">
          <div class="text-amber-100 font-semibold text-sm mb-2">Equipment</div>
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-2">
            <div *ngFor="let slot of slots" class="border border-amber-800/40 rounded-lg p-2">
              <div class="flex items-center gap-2 text-amber-300 text-xs">
                <svg class="w-4 h-4 text-amber-500" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                  <path [attr.d]="slot.icon" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" />
                </svg>
                <span>{{ slot.label }}</span>
              </div>
              <div class="mt-2 text-amber-100 text-xs">
                {{ getItemName(getEquippedItem(slot.slot)?.itemId) }}
              </div>
              <button
                *ngIf="getEquippedItem(slot.slot)"
                class="mt-2 text-[10px] px-2 py-1 rounded border border-amber-700/50 text-amber-300"
                (click)="unequip(slot.slot)"
              >
                Unequip
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
