// src/game/ui/TravelPanel.tsx
/**
 * TravelPanel - Travel progress and encounter UI
 *
 * Shows travel progress between locations and handles random encounters
 * that occur during travel.
 */

import { useEffect, useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useGameStore, type TravelState } from '../store/gameStore';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { Badge } from '@/components/ui/badge';

// ============================================================================
// ICONS
// ============================================================================

function HorseIcon({ className = '' }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      <path d="M22 10c-1-3-4-6-7-6-2 0-4 2-5 4-2-1-4-1-6 1-1 1-2 3-2 5 0 3 2 6 5 6h4l1 2h4l1-2h2c2 0 3-1 4-3 0-2-1-5-1-7z" />
      <path d="M5 11c0 1 1 2 2 2" />
    </svg>
  );
}

function TrainIcon({ className = '' }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      <rect x="4" y="3" width="16" height="14" rx="2" />
      <path d="M4 11h16" />
      <path d="M12 3v8" />
      <circle cx="8" cy="19" r="2" />
      <circle cx="16" cy="19" r="2" />
      <path d="M8 17h8" />
    </svg>
  );
}

function BootIcon({ className = '' }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      <path d="M7 21h10c1 0 2-1 2-2v-4c0-1-1-2-2-2h-1l-1-8c0-1-1-2-2-2H11c-1 0-2 1-2 2l-1 8H7c-1 0-2 1-2 2v4c0 1 1 2 2 2z" />
    </svg>
  );
}

function SkullIcon({ className = '' }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      <circle cx="12" cy="10" r="7" />
      <path d="M8 10a1 1 0 1 0 2 0 1 1 0 1 0-2 0" />
      <path d="M14 10a1 1 0 1 0 2 0 1 1 0 1 0-2 0" />
      <path d="M9 17v4h2v-2h2v2h2v-4" />
      <path d="M12 14v1" />
    </svg>
  );
}

// ============================================================================
// CONSTANTS
// ============================================================================

const DANGER_COLORS: Record<string, string> = {
  safe: 'text-green-400 bg-green-900/30 border-green-700',
  low: 'text-lime-400 bg-lime-900/30 border-lime-700',
  moderate: 'text-yellow-400 bg-yellow-900/30 border-yellow-700',
  high: 'text-orange-400 bg-orange-900/30 border-orange-700',
  extreme: 'text-red-400 bg-red-900/30 border-red-700',
};

const METHOD_INFO: Record<string, { icon: typeof HorseIcon; label: string; speed: string }> = {
  road: { icon: HorseIcon, label: 'Road', speed: 'Fast' },
  trail: { icon: BootIcon, label: 'Trail', speed: 'Moderate' },
  railroad: { icon: TrainIcon, label: 'Railroad', speed: 'Very Fast' },
  wilderness: { icon: BootIcon, label: 'Wilderness', speed: 'Slow' },
  river: { icon: HorseIcon, label: 'River', speed: 'Varies' },
};

// ============================================================================
// MAIN COMPONENT
// ============================================================================

export function TravelPanel() {
  const {
    travelState,
    loadedWorld,
    completeTravel,
    cancelTravel,
    startCombat,
  } = useGameStore();

  const [progress, setProgress] = useState(0);
  const [showEncounter, setShowEncounter] = useState(false);

  // Get location names
  const fromLocation = loadedWorld?.getLocation(travelState?.fromLocationId ?? '');
  const toLocation = loadedWorld?.getLocation(travelState?.toLocationId ?? '');

  // Animate travel progress
  useEffect(() => {
    if (!travelState) {
      setProgress(0);
      setShowEncounter(false);
      return;
    }

    // If there's an encounter, show it at 50% progress
    if (travelState.encounterId) {
      const timer = setTimeout(() => {
        setProgress(50);
        setTimeout(() => setShowEncounter(true), 500);
      }, 1000);
      return () => clearTimeout(timer);
    }

    // Normal travel - animate to 100%
    const duration = Math.min(travelState.travelTime * 200, 3000); // Cap at 3s
    const startTime = Date.now();

    const animate = () => {
      const elapsed = Date.now() - startTime;
      const newProgress = Math.min((elapsed / duration) * 100, 100);
      setProgress(newProgress);

      if (newProgress < 100) {
        requestAnimationFrame(animate);
      } else {
        // Travel complete
        setTimeout(() => completeTravel(), 500);
      }
    };

    requestAnimationFrame(animate);
  }, [travelState, completeTravel]);

  // Handle encounter fight
  const handleFight = useCallback(() => {
    if (travelState?.encounterId) {
      startCombat(travelState.encounterId);
    }
  }, [travelState, startCombat]);

  // Handle flee
  const handleFlee = useCallback(() => {
    cancelTravel();
  }, [cancelTravel]);

  // Handle continue after winning combat
  const handleContinue = useCallback(() => {
    completeTravel();
  }, [completeTravel]);

  if (!travelState) {
    return null;
  }

  const methodInfo = METHOD_INFO[travelState.method] || METHOD_INFO.trail;
  const MethodIcon = methodInfo.icon;
  const dangerClass = DANGER_COLORS[travelState.dangerLevel] || DANGER_COLORS.moderate;

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-50 flex items-center justify-center bg-stone-950/90"
      >
        <motion.div
          initial={{ scale: 0.9, y: 20 }}
          animate={{ scale: 1, y: 0 }}
          exit={{ scale: 0.9, y: 20 }}
          className="w-full max-w-md mx-4 bg-stone-900 border-2 border-amber-800/50 rounded-lg shadow-2xl overflow-hidden"
        >
          {/* Header */}
          <div className="bg-amber-900/30 border-b border-amber-800/50 p-4">
            <div className="flex items-center gap-3">
              <MethodIcon className="w-8 h-8 text-amber-400" />
              <div>
                <h2 className="text-lg font-bold text-amber-100">
                  {showEncounter ? 'Encounter!' : 'Traveling...'}
                </h2>
                <p className="text-sm text-amber-400">
                  {fromLocation?.ref.name ?? 'Unknown'} → {toLocation?.ref.name ?? 'Unknown'}
                </p>
              </div>
            </div>
          </div>

          {/* Content */}
          <div className="p-4 space-y-4">
            {/* Route Info */}
            <div className="flex items-center justify-between text-sm">
              <div className="flex items-center gap-2">
                <Badge variant="outline" className="bg-stone-800 text-amber-200 border-stone-700">
                  {methodInfo.label}
                </Badge>
                <span className="text-stone-400">{travelState.travelTime}h travel time</span>
              </div>
              <Badge className={`capitalize ${dangerClass}`}>
                {travelState.dangerLevel} danger
              </Badge>
            </div>

            {/* Progress Bar */}
            <div className="space-y-2">
              <Progress value={progress} className="h-3 bg-stone-800" />
              <div className="flex justify-between text-xs text-stone-500">
                <span>{fromLocation?.ref.name ?? 'Origin'}</span>
                <span>{Math.round(progress)}%</span>
                <span>{toLocation?.ref.name ?? 'Destination'}</span>
              </div>
            </div>

            {/* Encounter Panel */}
            {showEncounter && travelState.encounterId && (
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="bg-red-950/30 border border-red-800/50 rounded-lg p-4"
              >
                <div className="flex items-center gap-3 mb-3">
                  <SkullIcon className="w-8 h-8 text-red-400" />
                  <div>
                    <h3 className="font-bold text-red-200">Ambush!</h3>
                    <p className="text-sm text-red-400">
                      Hostiles have blocked the {travelState.method}!
                    </p>
                  </div>
                </div>

                <p className="text-stone-300 text-sm mb-4">
                  You've been waylaid by enemies. You can fight your way through or attempt to flee
                  back the way you came.
                </p>

                <div className="flex gap-3">
                  <Button
                    onClick={handleFight}
                    className="flex-1 bg-red-800 hover:bg-red-700 text-red-100"
                  >
                    Fight
                  </Button>
                  <Button
                    onClick={handleFlee}
                    variant="outline"
                    className="flex-1 border-stone-600 text-stone-300 hover:bg-stone-800"
                  >
                    Flee
                  </Button>
                </div>
              </motion.div>
            )}

            {/* Traveling Message (no encounter) */}
            {!showEncounter && !travelState.encounterId && (
              <div className="text-center py-4">
                <motion.div
                  animate={{ x: [0, 10, 0] }}
                  transition={{ repeat: Infinity, duration: 1 }}
                  className="inline-block"
                >
                  <MethodIcon className="w-12 h-12 text-amber-500 mx-auto" />
                </motion.div>
                <p className="text-stone-400 mt-2">
                  Traveling via {methodInfo.label.toLowerCase()}...
                </p>
              </div>
            )}
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}

export default TravelPanel;

// legacy/angular-ui/travel-panel.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnDestroy, OnInit } from '@angular/core';
import { animate, style, transition, trigger } from '@angular/animations';
import type { Subscription } from 'rxjs';

import type { LoadedWorld } from '@/data/worlds';
import type { DangerLevel, TravelMethod } from '@/data/schemas/world';
import type { TravelState } from '@/store';
import { GameStoreService } from '../services/game-store.service';

type DangerStyle = { badge: string; text: string };

type MethodInfo = { icon: 'horse' | 'train' | 'boot'; label: string; speed: string };

const DANGER_STYLES: Record<DangerLevel, DangerStyle> = {
  safe: {
    badge: 'bg-green-900/50 text-green-400 border-green-700/50',
    text: 'text-green-400',
  },
  low: {
    badge: 'bg-lime-900/50 text-lime-400 border-lime-700/50',
    text: 'text-lime-400',
  },
  moderate: {
    badge: 'bg-yellow-900/50 text-yellow-400 border-yellow-700/50',
    text: 'text-yellow-400',
  },
  high: {
    badge: 'bg-orange-900/50 text-orange-400 border-orange-700/50',
    text: 'text-orange-400',
  },
  extreme: {
    badge: 'bg-red-900/50 text-red-400 border-red-700/50',
    text: 'text-red-400',
  },
};

const METHOD_INFO: Record<TravelMethod, MethodInfo> = {
  road: { icon: 'horse', label: 'Road', speed: 'Fast' },
  trail: { icon: 'boot', label: 'Trail', speed: 'Moderate' },
  railroad: { icon: 'train', label: 'Railroad', speed: 'Very Fast' },
  wilderness: { icon: 'boot', label: 'Wilderness', speed: 'Slow' },
  river: { icon: 'horse', label: 'River', speed: 'Varies' },
};

@Component({
  selector: 'app-travel-panel',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './travel-panel.component.html',
  styleUrls: ['./travel-panel.component.scss'],
  animations: [
    trigger('overlay', [
      transition(':enter', [style({ opacity: 0 }), animate('150ms ease-out', style({ opacity: 1 }))]),
      transition(':leave', [animate('150ms ease-in', style({ opacity: 0 }))]),
    ]),
    trigger('panel', [
      transition(':enter', [
        style({ opacity: 0, transform: 'translateY(20px) scale(0.9)' }),
        animate('200ms ease-out', style({ opacity: 1, transform: 'translateY(0) scale(1)' })),
      ]),
      transition(':leave', [
        animate('180ms ease-in', style({ opacity: 0, transform: 'translateY(20px) scale(0.9)' })),
      ]),
    ]),
    trigger('encounter', [
      transition(':enter', [
        style({ opacity: 0, transform: 'translateY(10px)' }),
        animate('180ms ease-out', style({ opacity: 1, transform: 'translateY(0)' })),
      ]),
    ]),
  ],
})
export class TravelPanelComponent implements OnInit, OnDestroy {
  travel: TravelState | null = null;
  progress = 0;
  showEncounter = false;

  private subscription?: Subscription;
  private rafId?: number;
  private encounterTimer?: number;
  private revealEncounterTimer?: number;
  private completeTimer?: number;

  constructor(readonly gameStore: GameStoreService) {}

  ngOnInit(): void {
    this.subscription = this.gameStore.state$.subscribe((state) => {
      if (this.travel?.startedAt !== state.travelState?.startedAt) {
        this.resetProgress();
      }
      this.travel = state.travelState ?? null;
      if (!this.travel) {
        this.resetProgress();
        return;
      }

      if (this.travel.progress > 0) {
        this.progress = this.travel.progress;
      } else if (this.progress === 0 && !this.showEncounter) {
        this.beginTravelAnimation();
      }
    });
  }

  ngOnDestroy(): void {
    this.subscription?.unsubscribe();
    this.clearTimers();
  }

  get fromName(): string {
    return this.getLocationName(this.travel?.fromLocationId);
  }

  get toName(): string {
    return this.getLocationName(this.travel?.toLocationId);
  }

  get methodInfo(): MethodInfo {
    if (!this.travel) return METHOD_INFO.trail;
    return METHOD_INFO[this.travel.method] ?? METHOD_INFO.trail;
  }

  get dangerStyle(): DangerStyle {
    const level = this.travel?.dangerLevel ?? 'moderate';
    return DANGER_STYLES[level] ?? DANGER_STYLES.moderate;
  }

  get dangerClass(): string {
    return this.dangerStyle.text;
  }

  get progressPercent(): number {
    return this.progress;
  }

  get progressMarkerLeft(): number {
    return Math.min(this.progressPercent, 97);
  }

  completeTravel(): void {
    this.gameStore.actions().completeTravel();
  }

  cancelTravel(): void {
    this.gameStore.actions().cancelTravel();
  }

  fightEncounter(): void {
    if (this.travel?.encounterId) {
      this.gameStore.actions().startCombat(this.travel.encounterId);
    }
  }

  private beginTravelAnimation(): void {
    if (!this.travel) return;

    this.clearTimers();
    this.progress = 0;
    this.showEncounter = false;

    if (this.travel.encounterId) {
      this.encounterTimer = window.setTimeout(() => {
        this.progress = 50;
        this.revealEncounterTimer = window.setTimeout(() => {
          this.showEncounter = true;
        }, 500);
      }, 1000);
      return;
    }

    const duration = Math.min(this.travel.travelTime * 200, 3000);
    const startTime = Date.now();

    const animate = () => {
      const elapsed = Date.now() - startTime;
      const newProgress = Math.min((elapsed / duration) * 100, 100);
      this.progress = newProgress;

      if (newProgress < 100) {
        this.rafId = window.requestAnimationFrame(animate);
      } else {
        this.completeTimer = window.setTimeout(() => this.completeTravel(), 500);
      }
    };

    this.rafId = window.requestAnimationFrame(animate);
  }

  private resetProgress(): void {
    this.clearTimers();
    this.progress = 0;
    this.showEncounter = false;
  }

  private clearTimers(): void {
    if (this.rafId) {
      window.cancelAnimationFrame(this.rafId);
      this.rafId = undefined;
    }
    if (this.encounterTimer) {
      window.clearTimeout(this.encounterTimer);
      this.encounterTimer = undefined;
    }
    if (this.revealEncounterTimer) {
      window.clearTimeout(this.revealEncounterTimer);
      this.revealEncounterTimer = undefined;
    }
    if (this.completeTimer) {
      window.clearTimeout(this.completeTimer);
      this.completeTimer = undefined;
    }
  }

  private getLocationName(locationId?: string | null): string {
    if (!locationId) return 'Unknown';
    const world = this.gameStore.getState().loadedWorld as LoadedWorld | null;
    const location = world?.getLocation ? world.getLocation(locationId) : null;
    if (location?.ref?.name) return location.ref.name;
    return locationId;
  }
}
